[package]
name = "cavos"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.14.0"

[dev-dependencies]
snforge_std = "0.48.1"
assert_macros = "2.14.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[sncast.dev]                                         # Define a profile name
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_10/dql5pMT88iueZWl7L0yzT56uVk0EBU4L" # Url of the RPC provider
account = "my_account"
block-explorer = "Voyager"

[sncast.release]                                         # Define a profile name
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_10/dql5pMT88iueZWl7L0yzT56uVk0EBU4L" # Url of the RPC provider
account = "my_account"
block-explorer = "Voyager"