# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

# [sncast.default]                                         # Define a profile name
# url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8" # Url of the RPC provider
# accounts-file = "../account-file"                        # Path to the file with the account data
# account = "mainuser"                                     # Account from `accounts_file` or default account file that will be used for the transactions
# keystore = "~/keystore"                                  # Path to the keystore file
# wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
# block-explorer = "StarkScan"                             # Block explorer service used to display links to transaction details
# show-explorer-links = true                               # Print links pointing to pages with transaction details in the chosen block explorer

[sncast.sepolia]                                         # Define a profile name
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_8/dql5pMT88iueZWl7L0yzT56uVk0EBU4L" # Url of the RPC provider
# accounts-file = "../account-file"                        # Path to the file with the account data
# account = "mainuser"                                     # Account from `accounts_file` or default account file that will be used for the transactions
# keystore = "~/keystore"                                  # Path to the keystore file
# wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
# block-explorer = "StarkScan"                             # Block explorer service used to display links to transaction details
# show-explorer-links = true                               # Print links pointing to pages with transaction details in the chosen block explorer

[sncast.mainnet]                                         # Define a profile name
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_8/dql5pMT88iueZWl7L0yzT56uVk0EBU4L" # Url of the RPC provider
